### ISSUE TITLE
NameError: name 'idraw' is not defined

### ISSUE THREAD

**Issue by mostofthetime** [focccus/gpx_visualizer#1]
Hello @focccus ,

your project looks pretty good! When i use the visualizer.py i get this error:

--
Reduced from 534 to 73
Traceback (most recent call last):
  File "visualizer.py", line 100, in <module>
    idraw.rectangle([(10, 2 * size - 10), (170, 2 * size - 30)], fill="black")
NameError: name 'idraw' is not defined
--

regards

**Comment by Stevertus** [comment]
Thanks, never thought someone would like to use it :D 
In that version there is indeed a problem:
In Line 100 you would have to insert a if idraw: https://github.com/focccus/gpx_visualizer/blob/master/visualizer.py#L100
```python
if idraw: 
   idraw.rectangle([(10, 2 * size - 10), (170, 2 * size - 30)], fill="black")
```
Maybe I get to update it soon

**Comment by mostofthetime** [comment]
Thanks for the fast answer. It looks good for the gpx visualisation i have searched for.

After i insert a if idraw: at line 100 i become a another error. 
`Traceback (most recent call last):
  File "visualizer.py", line 100, in <module>
    if idraw:
NameError: name 'idraw' is not defined
`

I'm new in python and have read a couple of documentations. But i don't find the problem
